apiVersion: v1
kind: Namespace
metadata:
  name: python-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: python-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: aguyonnet/test-api:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: python-app
spec:
  selector:
    app: python-app
  type: LoadBalancer
  ports:
  - name: http
    port: 8000       # Port exposé côté LoadBalancer
    targetPort: 8000 # Port interne du conteneur
